### ISSUE TITLE
Flex Box Margin Problem

### ISSUE THREAD

**Issue by zicklag** [RAUI-labs/raui#55] opened 2021-05-13 20:35 UTC
I've got a simple layout where the margins in a flex box seem to be working incorrectly:

```rust
use raui::prelude::*;
use raui_quick_start::RauiQuickStartBuilder;

fn main() {
    RauiQuickStartBuilder::default()
        .window_title("RAUI Guide".into())
        .widget_tree(widget! {
            (app)
        })
        .build()
        .expect("Error building quick start")
        .run()
        .expect("Error running RAUI app");
}

pub fn app(_ctx: WidgetContext) -> WidgetNode {
    let text_box_props = Props::new(TextBoxProps {
        text: "Hello World!".into(),
        color: Color {
            r: 0.0,
            g: 0.0,
            b: 0.0,
            a: 1.0,
        },
        font: TextBoxFont {
            name: "resources/verdana.ttf".to_owned(),
            size: 60.0,
        },
        ..Default::default()
    })
    .with(FlexBoxItemLayout {
        margin: Rect {
            top: 50., // Set a margin above our text
            ..Default::default()
        },
        ..Default::default()
    });

    let image_box_props = Props::new(ImageBoxProps {
        material: ImageBoxMaterial::Image(ImageBoxImage {
            id: "resources/cats.jpg".to_owned(),
            ..Default::default()
        }),
        ..Default::default()
    });

    widget! {
        (vertical_box [
            (text_box: {text_box_props})
            (image_box: {image_box_props})
        ])
    }
}

```

![image](https://user-images.githubusercontent.com/25393315/118183903-496fde80-b400-11eb-9e44-838eb92556a4.png)

While the margin above the text _is_ applying extra space, the cat picture seems to also get extra space added to the bottom for some reason.

If I take out the margin on the text it, the space at the bottom of the image disappears:

![image](https://user-images.githubusercontent.com/25393315/118184181-a4a1d100-b400-11eb-9e9c-f234ac6e1981.png)

The same thing happens if I add a margin to the bottom of the text: an extra myserious space is added to the bottom of the cat picture.

**Comment by zicklag** [comment] 2021-05-13 21:00
I'm also finding that `shrink` and `grow` dont' seem to effecting anything as far as I can tell.

I curious whether or not it would make sense to build a layout engine based on [`stretch`](https://github.com/vislyhq/stretch). Obviously the point of the design is that anybody could bring their own layout engine, which is great, but I wonder if that would be useful in the default layout engine to make it actually flex-box compliant.

It would add an extra 2.1k lines of code dependency ( I did a quick line count, not counting comments ), but that isn't too bad. And stretch is optimized for small code size and performance on mobile so it seems like it could be a good fit. 

Not sure if there are any other problems with that approach, though, and I'm not sure if this are easy fixes anyway.

**Comment by PsichiX** [comment] 2021-05-14 07:42
gonna investigate the problem this evening. i have concerns when it comes to using stretch, iirc bevy was using it and there were performance issues? have to research this to be sure.

**Comment by PsichiX** [comment] 2021-05-15 12:52
ok, i'v reviewed PR that is linked to this issue, i'll start investigation of this problem soon, fix the bugs and produce an explanation of how layouting works and clarify where and how RAUI flex box is different from CSS flex box.

quick question: can we easily add to the book a whole separate section where i could put explanation of how default layout engine does layouting?

**Comment by PsichiX** [comment] 2021-05-15 12:56
also in the future we could try to prototype a separate layout plugin that uses stretch, that would let ppl use it if they prefer to follow mores CSS-ish flex box layouting 🤔 that's something to consider.

**Comment by zicklag** [comment] 2021-05-15 13:52
> i'll start investigation of this problem soon, fix the bugs and produce an explanation of how layouting works and clarify where and how RAUI flex box is different from CSS flex box.

:heart: :+1:

> quick question: can we easily add to the book a whole separate section where i could put explanation of how default layout engine does its layouting?

Absolutely. That's really easy.

I could create a PR with the stub section so that you could add the actual content to if that helps.

> also in the future we could try to prototype a separate layout plugin that uses stretch, that would let ppl use it if they prefer to follow mores CSS-ish flex box layouting thinking that's something to consider, gonna add a separate issue for that later and mark it as help wanted so someone could pick that up if they want.

I like that idea.

**Comment by PsichiX** [comment] 2021-05-16 20:14
i was debugging the margin problem - accounting for margin in flex box layouting is definitely and completely broken:
![image](https://user-images.githubusercontent.com/2111867/118411250-ded6d100-b693-11eb-83c7-ba99dbe7d41e.png)

i have idea where the source of the problem is, i'm implementing and testing the solution.

**Comment by PsichiX** [comment] 2021-05-16 21:25
FIXED!
![image](https://user-images.githubusercontent.com/2111867/118413088-c2d82d00-b69d-11eb-8733-d98ed2cb57fb.png)

The problem was that after layouting child item, i was progressing `new_main` axis with only that child available space size and i wasn't accounting its margins so relative offset of next items was made without previous item margins 🤦

**Comment by PsichiX** [comment] 2021-05-16 22:39
changes are pushed to `next`, tomorrow i'll add an explanation of default layout engine. i'm closing this issue now, feel free to test it :D

**Closed by PsichiX** 2021-05-16 22:39 UTC

**Comment by zicklag** [comment] 2021-05-17 17:06
Works!

![Uploading image.png…]()
